services:
  - type: web
    name: al-assile-mobile
    runtime: docker
    plan: free
    region: frankfurt
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: SYNC_API_KEY
        generateValue: true
      - key: NODE_ENV
        value: production
